# netlify.toml (Versão com comando de build explícito)

[build]
  # ESTA É A NOVA LINHA:
  command = "pip install -r netlify/functions/requirements.txt"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
