[build]
  command = "pip install -r netlify/functions/requirements.txt"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
